### PR TITLE
added django_extensions, which lets us generate object model diagrams

### PR DESCRIPTION
**Pull request by aykamko**
Requires graphviz and pygraphviz
    
    brew install graphviz
    pip install pygraphviz

### CODE REVIEW

**Comment by noahsark769** [comment]
Do we need this? Is there at least a way to make it only generate a graph with the models from our apps instead of django_facebook, django_cms, etc

**Comment by noahsark769** [comment]
(When I say do we need this, I mean wouldn't it really just be simpler to draw out the database diagram that we need by hand? That graph is so huge and it seems like overkill)

**Comment by SamLau95** [comment]
It is pretty hard for me to know where to start looking for this visualization ; is there a way to ignore models?

**Comment by noahsark769** [comment]
^ that's what im sayin

**Comment by noahsark769** [comment]
Okay imma close this, we can revisit it if we really need to

**Pull request closed without merging**
