### PR TITLE
Finish up homepage

### PR DESCRIPTION
**Pull request by noahsark769**
This should be it for #63 

1. Adds a nice little header describing the project badges
2. Infographic on the homepage - we should check with Andreas to figure out if we can get access to an svg of this
3. Quick improvement: the project badges underline themselves on hover

Divider 1:
screen shot 2015-01-12 at 5 35 49 pm

Divider 2:
screen shot 2015-01-12 at 5 35 54 pm

On mobile the infographic is too small to see, so I just put a learn more link instead:
screen shot 2015-01-12 at 5 35 40 pm

@vivekraghuram let me know if this looks good to you then I'll merge it!

### CODE REVIEW

**Comment by vivekraghuram** [comment]
@noahsark769 do you think the link on the mobile version should be a button instead?

**Comment by vivekraghuram** [comment]
Otherwise everything looks good to me. I say merge it!

**Comment by noahsark769** [comment]
Good idea, I'll add that in

**Comment by noahsark769** [comment]
screen shot 2015-01-18 at 9 33 12 pm

How's that look to you, @vivekraghuram

**Comment by vivekraghuram** [comment]
Looks good to me!

**Comment by noahsark769** [comment]
Mergelicious

**Pull request merged**
