### PR TITLE
Admin list emails

### PR DESCRIPTION
**Pull request by erictshen**
Added means for admin to acquire list of emails, and updated admin dashboard to have more than one page.

Also updated git ignore very quickly for some static files

### CODE REVIEW

**Comment by erictshen** [comment]
What second layer of tabs looks like. Let me know any feedback. I think it could be better, but not sure how to design it better.

screen shot 2015-02-23 at 10 10 28 pm

**Comment by erictshen** [comment]
The pull request is currently not completed, will update it soon!

**Comment by noahsark769** [comment]
I think the nested tabs could definitely at least be a little bit smaller to differentiate them, let me know when it's done and I'll check it out!

**Comment by noahsark769** [comment]
Wait what would be in revolv/static/revolv/static?

**Comment by erictshen** [comment]
Deleting this pull request and making a new one b/c I messed up git stuff...

**Pull request closed without merging**
