### PR TITLE
Sameera donation modal share buttons

### PR DESCRIPTION
**Pull request by sameerav**
super short pull request to add share buttons to the donation modal - addresses #308 
review @noahsark769 ?

### CODE REVIEW

**Comment by noahsark769** [comment]
@sameerav can I get a screen cap?

**Comment by sameerav** [comment]
screen shot 2015-06-03 at 5 31 38 pm

my bad, here it is

**Comment by noahsark769** [comment]
So what happens when you click on the Facebook button? What exactly are you sharing a link to, the project page? Also what does the headline if the link say when you share it? The guys from IDEO were saying how important that was so I figure we should make sure it works

**Comment by sameerav** [comment]
screen shot 2015-06-03 at 5 52 54 pm

it does something like this, opens up a window with the link to the project page.
What do you mean by headline?

**Comment by noahsark769** [comment]
By headline, I mean the place where "127.0.0.1" is right now. The sharing isn't get effective if all the Facebook post days is the IP address haha. Is there a way to change that?

**Comment by noahsark769** [comment]
Says*

**Comment by sameerav** [comment]
Hm I think when its on the actual site it'll be a link to the revolv site, but yeah I agree that should be changed to the "I donated, why don't you?" that's in the issue title or something like that

I'll look into it!

**Comment by noahsark769** [comment]
Yup, I bet "I donated to <project name>, won't you?" would be a good one

**Comment by noahsark769** [comment]
Four years later, this repo is no longer the canonical RE-volv repo. Going to close this to get it out of my Pull Request list. Also, hi @sameerav!

**Pull request closed without merging**
