### PR TITLE
removed the project review view and its corresponding redirects

### PR DESCRIPTION
**Pull request by sameerav**
removed the project review page class and its redirects and its url

### CODE REVIEW

**Comment by noahsark769** [comment]
1. Codeship is unhappy, it seems you didn't take the review urls out of the tests
2. Will this still work? Like, will POSTing to view instead of review in the project controls partial actually complete/deny/etc the project? I feel like it won't?

**Comment by noahsark769** [comment]
I think that you may have to leave in the view, but you can still take out the URLs, templates, etc

**Comment by noahsark769** [comment]
In particular, we don't need `review_project.html`

**Comment by noahsark769** [comment]
In any case, you should actually check that approve/deny/draft/post updates buttons and stuff still work. I wish we had tests for these, but those are in the pipeline in #227

**Comment by sameerav** [comment]
oh you're right it doesn't work :(
i'll put the view and the url and change the form post urls back but add http_method_names = [u'post']
to the view so you can't see it

**Comment by noahsark769** [comment]
Sounds great!

**Comment by noahsark769** [comment]
@sameerav you should update this with master :)

**Comment by noahsark769** [comment]
This is great, thanks!

**Pull request merged**
