### PR TITLE
CMSifying the header bar and the footer bar

### LINKED ISSUE #301: CMSify the footer bar
Should have the same structure as the nav bar!

### LINKED ISSUE #339: Formatting screwed up with too many nav bar items
screen shot 2015-06-08 at 5 54 40 pm

### LINKED ISSUE #343: We should have cursor: pointer on the reinvestment votes UI
Just a small thing, the cursor is a text pointer right now, which doesn't seem to afford clicking. Should make it `cursor: pointer`

### PR DESCRIPTION
**Pull request by noahsark769**
Fixes #339, fixes #301, fixes #343 

Footer and headers now actually are CMSified! There was a bunch of stuff with foundation we were doing wrong. Also, broke the tagline in the nav bar onto two lines as per #240, and fixed #343 cause it was a one line change.

Also, I added database seeds for wagtail pages! You can run `python manage.py seed --spec cms` to put in a whole bunch of pages with the same titles as the pages on RE-volv's actual website right now.

ALSO, I added in a new font-weight for Lato which we have supposedly been using all this time but it's never worked.

@vivekraghuram or @andylouisqin if either of you can give an LGTM then I'll merge this!

screen shot 2015-06-09 at 7 27 02 pm
screen shot 2015-06-09 at 7 27 14 pm
screen shot 2015-06-09 at 7 27 35 pm

### CODE REVIEW

**Comment by vivekraghuram** [comment]
Isn't that a bit too much space in the footer? The row with the logo looks very empty.

**Comment by noahsark769** [comment]
Yeah, the thing was that if I put the links alongside the logo, the links
got all compressed and hard to read. Although that was before I took the
font size down, so I can try it again

**Comment by noahsark769** [comment]
@vivekraghuram how's this look to you?

screen shot 2015-06-10 at 2 57 51 pm

**Comment by vivekraghuram** [comment]
lgtm

**Comment by noahsark769** [comment]
Sweet! Will merge this then

**Pull request merged**
