### PR TITLE
made sexy re-usable modal framework; finished payments modal

### PR DESCRIPTION
**Pull request by aykamko**
Modal at `medium` screens and up.
aleks-payment_modal1

Modal at `small` screens and lower (expands to entire page)
aleks-payment_modal2

### CODE REVIEW

**Comment by aykamko** [comment]
NOTE: I haven't tested form verification, i'll probably do that later in the next couple of days

**Comment by noahsark769** [comment]
Nice! (1) can you open an issue for the validation? (2) why import the project file in main? Seems like it would be better to just put the project scss file on the project page. (3) Travis is unhappy :(

**Comment by SamLau95** [comment]
The Travis output sure is hard to read :(

**Comment by noahsark769** [comment]
Looks like there's one test erroring and one failing:

```
======================================================================
ERROR: test_form_process_payment (revolv.payments.tests.forms.test_credit_card_donation_form.CreditCardDonationFormTestCase)
Verify that we can process a payment with the form.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/calblueprint/revolv/revolv/payments/tests/forms/test_credit_card_donation_form.py", line 47, in test_form_process_payment
    cc_form.process_payment(mock_project, mock_pt)
  File "/home/travis/build/calblueprint/revolv/revolv/payments/forms.py", line 48, in process_payment
    raise Exception('Cannot process invalid form')
Exception: Cannot process invalid form
======================================================================
FAIL: test_valid_form (revolv.payments.tests.forms.test_credit_card_donation_form.CreditCardDonationFormTestCase)
Verify that a valid form is valid.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/calblueprint/revolv/revolv/payments/tests/forms/test_credit_card_donation_form.py", line 20, in test_valid_form
    self.assertTrue(cc_form.is_valid())
AssertionError: False is not true
----------------------------------------------------------------------
Ran 46 tests in 8.357s
FAILED (failures=1, errors=1)
```

**Comment by aykamko** [comment]
1) Making an issue for validation and assigning it to myself.

2) Moved `project.scss` out of `main` and into the project template.

3) Should have just fixed Travis tests. The CreditCard validation tests was using an `2014` as its expiration year... which means it's an expired card LOL. Changed the test to use `2020` instead.

4) Shouldn't we add `revolv/static/.css` to the gitignore? I keep having to be careful not to add compiled css files to my diff

**Comment by aykamko** [comment]
Went ahead and did 4) from above. Let me know if that's not what you want and I'll reset

**Comment by noahsark769** [comment]
Actually, just go ahead and commit the compiled files for now. Having them committed to the repo is kind of meh, but it allows us to serve them right from heroku without having to have any compilation step (as opposed to having to serve them off of aws, etc). Really, we should build the compiled files and push them to AWS as part of the deploy process, and I think we'll probably figure that out as part of #135 but right now let's not worry about it and just commit the CSS haha

**Comment by noahsark769** [comment]
Great job man, gunna merge this!

**Pull request merged**
