### PR TITLE
New styles for login page

### PR DESCRIPTION
**Pull request by noahsark769**
For #111. I'm excited about this, they're so much better than the old ones and they animate between login/signup! I'd like at least one review before merging this so can someone look over it? Maybe @sameerav or @aykamko 

screen shot 2015-02-10 at 1 41 06 am
screen shot 2015-02-10 at 1 41 15 am
screen shot 2015-02-10 at 1 41 31 am
screen shot 2015-02-10 at 1 41 44 am

### CODE REVIEW

**Comment by sameerav** [comment]
I like these a lot! I don't know if it does this right now but it might look cool to have the login button fill in when you hover above it

Also, for the case where the user didn't enter a username or password, it might be better to just highlight the box - the full red fill is a little overwhelming

**Comment by noahsark769** [comment]
Yup, it fills in the box on hover! Also yeah, let me are if I can get it to
look good with just a red border

**Comment by andylouisqin** [comment]
These look slick @noahsark769! Stamp of approval.

**Comment by noahsark769** [comment]
Thanks @andylouisqin! @sameerav thanks for the suggestion on highlighting with border instead, I think it looks much nicer. What do you think?

screen shot 2015-02-10 at 10 40 17 am

**Pull request merged**
