### PR TITLE
Fixed bug in typeahead address selector

### LINKED ISSUE #270: Address autocomplete and maps on project pages are totally broken
I think these two things are related

### PR DESCRIPTION
**Pull request by erictshen**
Fixes #270 

Bug was caused by the html div element for the map not actually being present in the html.

For projects that are currently buggy on staging, editing them and updating the address to a new one should fix things.

### CODE REVIEW

**Comment by erictshen** [comment]
screen shot 2015-05-21 at 5 32 19 pm

Screenshot of what the fixed page looks like!

**Comment by noahsark769** [comment]
Wow nice @erictshen! Is it possible you can offset the CSS for the autocomplete popup so that it touches the text box? Other than that, this looks good

**Comment by erictshen** [comment]
Updated it so the popup is closer to the textbox! Let me know if it looks good.

screen shot 2015-05-21 at 7 03 37 pm

**Comment by noahsark769** [comment]
Looks great! Will merge when codeship passes!

**Pull request merged**
